openapi: 3.0.1
info:
  title: CIE API - MINT
  description: Servizio cie per Ministero degli Interni
  version: '1.0'
servers:
  - url: https://api.uat.p4pa.pagopa.it/pu/cie/mint
paths:
  /payments:
    get:
      tags:
        - mint
      summary: Retrieve a paged list of CIE payments
      description: Retrieve a paged list of CIE payments
      operationId: mintGetPayments
      parameters:
        - name: orgFiscalCode
          in: query
          schema:
            type: string
        - name: completionDateFrom
          in: query
          schema:
            type: string
            format: date-time
        - name: completionDateTo
          in: query
          schema:
            type: string
            format: date-time
        - name: paymentDateFrom
          in: query
          schema:
            type: string
            format: date-time
        - name: paymentDateTo
          in: query
          schema:
            type: string
            format: date-time
        - name: page
          in: query
          description: Zero-based page index (0..N)
          schema:
            minimum: 0.0
            type: integer
            default: 0
        - name: size
          in: query
          description: The size of the page to be returned
          schema:
            minimum: 1.0
            type: integer
            default: 20
        - name: sort
          in: query
          description: 'Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.'
          schema:
            type: array
            items:
              type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PagedPaymentCieDTO'
              example:
                content:
                  - status: UNPAID
                    paymentDate: string
                    completionDate: string
                    nav: string
                    reasonCode: string
                    reasonDescription: string
                    orgFiscalCode: string
                    orgName: string
                    orgAmountCents: 0
                    mefAmountCents: 0
                size: 0
                totalElements: 0
                totalPages: 0
                number: 0
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PagedPaymentCieDTO'
              example:
                content:
                  - status: UNPAID
                    paymentDate: string
                    completionDate: string
                    nav: string
                    reasonCode: string
                    reasonDescription: string
                    orgFiscalCode: string
                    orgName: string
                    orgAmountCents: 0
                    mefAmountCents: 0
                size: 0
                totalElements: 0
                totalPages: 0
                number: 0
        '401':
          description: Unauthorized - Missing or invalid token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PagedPaymentCieDTO'
              example:
                content:
                  - status: UNPAID
                    paymentDate: string
                    completionDate: string
                    nav: string
                    reasonCode: string
                    reasonDescription: string
                    orgFiscalCode: string
                    orgName: string
                    orgAmountCents: 0
                    mefAmountCents: 0
                size: 0
                totalElements: 0
                totalPages: 0
                number: 0
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PagedPaymentCieDTO'
              example:
                content:
                  - status: UNPAID
                    paymentDate: string
                    completionDate: string
                    nav: string
                    reasonCode: string
                    reasonDescription: string
                    orgFiscalCode: string
                    orgName: string
                    orgAmountCents: 0
                    mefAmountCents: 0
                size: 0
                totalElements: 0
                totalPages: 0
                number: 0
components:
  schemas:
    DebtPositionCieStatus:
      enum:
        - UNPAID
        - PAID
        - BURNED
        - REFUNDED
      type: string
    PagedPaymentCieDTO:
      required:
        - content
        - number
        - size
        - totalElements
        - totalPages
      type: object
      properties:
        content:
          type: array
          items:
            $ref: '#/components/schemas/PaymentCieDTO'
        size:
          type: integer
          format: int64
        totalElements:
          type: integer
          format: int64
        totalPages:
          type: integer
          format: int64
        number:
          type: integer
          format: int64
    PaymentCieDTO:
      required:
        - mefAmountCents
        - nav
        - orgAmountCents
        - orgFiscalCode
        - orgName
        - reasonCode
        - reasonDescription
        - status
      type: object
      properties:
        status:
          $ref: '#/components/schemas/DebtPositionCieStatus'
        paymentDate:
          type: string
          description: Payment date and time
          format: date-time
        completionDate:
          type: string
          description: Date and time when the payment was consumed for the CIE issuance
          format: date-time
        nav:
          type: string
          description: Unique payment identifier
        reasonCode:
          type: string
          description: Reason code
        reasonDescription:
          type: string
          description: Reason description
        orgFiscalCode:
          type: string
          description: Organization fiscal code
        orgName:
          type: string
          description: Organization name
        orgAmountCents:
          type: integer
          description: Amount due to the organization
          format: int64
        mefAmountCents:
          type: integer
          description: Amount due to MEF
          format: int64
tags:
  - name: mint
    description: Api for Ministero degli Interni