{
    "openapi": "3.0.1",
    "info": {
        "title": "Migration API",
        "description": "Servizio migration per Piattaforma Unitaria",
        "version": "1.0"
    },
    "servers": [
        {
            "url": "https://api.p4pa.pagopa.it/pu/migration"
        }
    ],
    "paths": {
        "/organization/{orgIpaCode}/{migrationFileType}": {
            "post": {
                "tags": [
                    "migration-file"
                ],
                "summary": "uploadMigrationFlowFile",
                "description": "Service to store an migration file",
                "operationId": "uploadMigrationFile",
                "parameters": [
                    {
                        "name": "orgIpaCode",
                        "in": "path",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "name": "migrationFileType",
                        "in": "path",
                        "required": true,
                        "schema": {
                            "$ref": "#/components/schemas/MigrationFileTypeEnum"
                        }
                    }
                ],
                "requestBody": {
                    "content": {
                        "multipart/form-data": {
                            "schema": {
                                "required": [
                                    "migrationFile"
                                ],
                                "properties": {
                                    "migrationFile": {
                                        "type": "string",
                                        "format": "binary"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "Created",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/UploadMigrationFileResponseDTO"
                                },
                                "example": {
                                    "uploadId": 0,
                                    "workflowId": "string",
                                    "runId": "string"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Server Error",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ErrorDTO"
                                },
                                "example": {
                                    "code": "NOT_FOUND",
                                    "message": "string",
                                    "traceId": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/organization/{orgIpaCode}": {
            "get": {
                "tags": [
                    "migration-file"
                ],
                "summary": "getMigrationFlows",
                "description": "Service to retrieve upload request statuses",
                "operationId": "getMigrationUploads",
                "parameters": [
                    {
                        "name": "orgIpaCode",
                        "in": "path",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "name": "migrationFileType",
                        "in": "query",
                        "schema": {
                            "$ref": "#/components/schemas/MigrationFileTypeEnum"
                        }
                    },
                    {
                        "name": "status",
                        "in": "query",
                        "schema": {
                            "$ref": "#/components/schemas/UploadsStatusEnum"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Created",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/components/schemas/Uploads"
                                    }
                                },
                                "example": [
                                    {
                                        "creationDate": "string",
                                        "updateDate": "string",
                                        "updateOperatorExternalId": "string",
                                        "updateTraceId": "string",
                                        "uploadId": 0,
                                        "organizationId": 0,
                                        "filePathName": "string",
                                        "fileName": "string",
                                        "fileSize": 0,
                                        "fileType": "ORGANIZATIONS",
                                        "status": "UPLOADED",
                                        "errorDescription": "string",
                                        "numTotalFiles": 0,
                                        "numCorrectlyProcessedFiles": 0
                                    }
                                ]
                            }
                        }
                    },
                    "500": {
                        "description": "Server Error",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ErrorDTO"
                                },
                                "example": {
                                    "code": "NOT_FOUND",
                                    "message": "string",
                                    "traceId": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/organization/{orgIpaCode}/migrations/{uploadId}": {
            "get": {
                "tags": [
                    "migration-file"
                ],
                "summary": "getMigrationFlow",
                "description": "Service to retrieve an upload request",
                "operationId": "getMigrationUpload",
                "parameters": [
                    {
                        "name": "orgIpaCode",
                        "in": "path",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "name": "uploadId",
                        "in": "path",
                        "required": true,
                        "schema": {
                            "type": "integer",
                            "format": "int64"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Created",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Uploads"
                                },
                                "example": {
                                    "creationDate": "string",
                                    "updateDate": "string",
                                    "updateOperatorExternalId": "string",
                                    "updateTraceId": "string",
                                    "uploadId": 0,
                                    "organizationId": 0,
                                    "filePathName": "string",
                                    "fileName": "string",
                                    "fileSize": 0,
                                    "fileType": "ORGANIZATIONS",
                                    "status": "UPLOADED",
                                    "errorDescription": "string",
                                    "numTotalFiles": 0,
                                    "numCorrectlyProcessedFiles": 0
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Server Error",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ErrorDTO"
                                },
                                "example": {
                                    "code": "NOT_FOUND",
                                    "message": "string",
                                    "traceId": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/organization/{orgIpaCode}/migrations/{uploadId}/errors": {
            "get": {
                "tags": [
                    "migration-file"
                ],
                "summary": "getMigrationErrors",
                "description": "Service to retrieve errors on an upload request",
                "operationId": "getMigrationErrors",
                "parameters": [
                    {
                        "name": "orgIpaCode",
                        "in": "path",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "name": "uploadId",
                        "in": "path",
                        "required": true,
                        "schema": {
                            "type": "integer",
                            "format": "int64"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ZIP file containing error files",
                        "content": {
                            "application/octet-stream": {
                                "schema": {
                                    "type": "string",
                                    "format": "binary"
                                },
                                "examples": {
                                    "default": {
                                        "value": null
                                    }
                                }
                            }
                        }
                    },
                    "204": {
                        "description": "No Content - No Errors Found",
                        "content": {
                            "application/octet-stream": {
                                "schema": {
                                    "type": "string",
                                    "format": "binary"
                                },
                                "examples": {
                                    "default": {
                                        "value": null
                                    }
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized - Missing or invalid token",
                        "content": {
                            "application/octet-stream": {
                                "schema": {
                                    "type": "string",
                                    "format": "binary"
                                },
                                "examples": {
                                    "default": {
                                        "value": null
                                    }
                                }
                            }
                        }
                    },
                    "403": {
                        "description": "Forbidden - No upload in error state",
                        "content": {
                            "application/octet-stream": {
                                "schema": {
                                    "type": "string",
                                    "format": "binary"
                                },
                                "examples": {
                                    "default": {
                                        "value": null
                                    }
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found - Upload not found",
                        "content": {
                            "application/octet-stream": {
                                "schema": {
                                    "type": "string",
                                    "format": "binary"
                                },
                                "examples": {
                                    "default": {
                                        "value": null
                                    }
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error - Error during errors processing",
                        "content": {
                            "application/octet-stream": {
                                "schema": {
                                    "type": "string",
                                    "format": "binary"
                                },
                                "examples": {
                                    "default": {
                                        "value": null
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/organization/{orgIpaCode}/migrations/{uploadId}/details": {
            "get": {
                "tags": [
                    "migration-file"
                ],
                "summary": "getMigrationFlowDetails",
                "description": "Service to retrieve upload request details",
                "operationId": "getMigrationUploadDetails",
                "parameters": [
                    {
                        "name": "orgIpaCode",
                        "in": "path",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "name": "uploadId",
                        "in": "path",
                        "required": true,
                        "schema": {
                            "type": "integer",
                            "format": "int64"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Created",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/components/schemas/UploadDetails"
                                    }
                                },
                                "example": [
                                    {
                                        "creationDate": "string",
                                        "updateDate": "string",
                                        "updateOperatorExternalId": "string",
                                        "updateTraceId": "string",
                                        "uploadDetailId": 0,
                                        "uploadId": 0,
                                        "organizationId": 0,
                                        "ingestionFlowFileId": 0,
                                        "ingestionFlowFileType": "RECEIPT",
                                        "filePathName": "string",
                                        "fileName": "string",
                                        "fileSize": 0,
                                        "status": "UPLOADED",
                                        "errorDescription": "string",
                                        "discardFileName": "string",
                                        "numTotalRows": 0,
                                        "numCorrectlyImportedRows": 0
                                    }
                                ]
                            }
                        }
                    },
                    "500": {
                        "description": "Server Error",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ErrorDTO"
                                },
                                "example": {
                                    "code": "NOT_FOUND",
                                    "message": "string",
                                    "traceId": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/organization/{orgIpaCode}/migrations/{uploadId}/details/{uploadDetailsId}": {
            "get": {
                "tags": [
                    "migration-file"
                ],
                "summary": "getMigrationFlowDetail",
                "description": "Service to retrieve upload request detail",
                "operationId": "getMigrationUploadDetail",
                "parameters": [
                    {
                        "name": "orgIpaCode",
                        "in": "path",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "name": "uploadId",
                        "in": "path",
                        "required": true,
                        "schema": {
                            "type": "integer",
                            "format": "int64"
                        }
                    },
                    {
                        "name": "uploadDetailsId",
                        "in": "path",
                        "required": true,
                        "schema": {
                            "type": "integer",
                            "format": "int64"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Created",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/UploadDetails"
                                },
                                "example": {
                                    "creationDate": "string",
                                    "updateDate": "string",
                                    "updateOperatorExternalId": "string",
                                    "updateTraceId": "string",
                                    "uploadDetailId": 0,
                                    "uploadId": 0,
                                    "organizationId": 0,
                                    "ingestionFlowFileId": 0,
                                    "ingestionFlowFileType": "RECEIPT",
                                    "filePathName": "string",
                                    "fileName": "string",
                                    "fileSize": 0,
                                    "status": "UPLOADED",
                                    "errorDescription": "string",
                                    "discardFileName": "string",
                                    "numTotalRows": 0,
                                    "numCorrectlyImportedRows": 0
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Server Error",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ErrorDTO"
                                },
                                "example": {
                                    "code": "NOT_FOUND",
                                    "message": "string",
                                    "traceId": "string"
                                }
                            }
                        }
                    }
                }
            }
        }
    },
    "components": {
        "schemas": {
            "UploadMigrationFileResponseDTO": {
                "required": [
                    "runId",
                    "uploadId",
                    "workflowId"
                ],
                "type": "object",
                "properties": {
                    "uploadId": {
                        "type": "integer",
                        "format": "int64"
                    },
                    "workflowId": {
                        "type": "string"
                    },
                    "runId": {
                        "type": "string"
                    }
                }
            },
            "CodeEnum": {
                "enum": [
                    "NOT_FOUND",
                    "BAD_REQUEST",
                    "GENERIC_ERROR",
                    "FILE_UPLOAD_ERROR",
                    "INVALID_FILE",
                    "FORBIDDEN"
                ],
                "type": "string"
            },
            "ErrorDTO": {
                "required": [
                    "code",
                    "message"
                ],
                "type": "object",
                "properties": {
                    "code": {
                        "$ref": "#/components/schemas/CodeEnum"
                    },
                    "message": {
                        "type": "string"
                    },
                    "traceId": {
                        "type": "string",
                        "nullable": true
                    }
                }
            },
            "MigrationFileTypeEnum": {
                "enum": [
                    "ORGANIZATIONS",
                    "ORG_SIL_SERVICES",
                    "DEBT_POSITIONS_TYPE",
                    "DEBT_POSITIONS_TYPE_ORG",
                    "DEBT_POSITIONS_TYPE_ORG_OPERATORS",
                    "PAYMENT_NOTIFICATION",
                    "PAYMENTS_REPORTING",
                    "TREASURY_CSV_COMPLETE",
                    "ASSESSMENTS",
                    "ASSESSMENTS_REGISTRY",
                    "DEBT_POSITIONS",
                    "DEBT_POSITIONS_PAID"
                ],
                "type": "string"
            },
            "Uploads": {
                "required": [
                    "fileName",
                    "filePathName",
                    "fileSize",
                    "fileType",
                    "organizationId",
                    "status"
                ],
                "type": "object",
                "properties": {
                    "creationDate": {
                        "type": "string",
                        "format": "date-time"
                    },
                    "updateDate": {
                        "type": "string",
                        "format": "date-time"
                    },
                    "updateOperatorExternalId": {
                        "type": "string"
                    },
                    "updateTraceId": {
                        "type": "string"
                    },
                    "uploadId": {
                        "type": "integer",
                        "format": "int64"
                    },
                    "organizationId": {
                        "type": "integer",
                        "format": "int64"
                    },
                    "filePathName": {
                        "type": "string"
                    },
                    "fileName": {
                        "type": "string"
                    },
                    "fileSize": {
                        "type": "integer",
                        "format": "int64"
                    },
                    "fileType": {
                        "$ref": "#/components/schemas/MigrationFileTypeEnum"
                    },
                    "status": {
                        "$ref": "#/components/schemas/UploadsStatusEnum"
                    },
                    "errorDescription": {
                        "type": "string"
                    },
                    "numTotalFiles": {
                        "type": "integer",
                        "format": "int32"
                    },
                    "numCorrectlyProcessedFiles": {
                        "type": "integer",
                        "format": "int32"
                    }
                }
            },
            "UploadsStatusEnum": {
                "enum": [
                    "UPLOADED",
                    "PROCESSING",
                    "COMPLETED",
                    "ERROR"
                ],
                "type": "string"
            },
            "IngestionFlowFileStatus": {
                "enum": [
                    "UPLOADED",
                    "PROCESSING",
                    "COMPLETED",
                    "ERROR",
                    "WAITING_FILE",
                    "WARNING"
                ],
                "type": "string"
            },
            "IngestionFlowFileTypeEnum": {
                "enum": [
                    "RECEIPT",
                    "RECEIPT_PAGOPA",
                    "PAYMENTS_REPORTING",
                    "PAYMENTS_REPORTING_PAGOPA",
                    "TREASURY_OPI",
                    "TREASURY_CSV",
                    "TREASURY_XLS",
                    "TREASURY_POSTE",
                    "TREASURY_CSV_COMPLETE",
                    "DP_INSTALLMENTS",
                    "PAYMENT_NOTIFICATION",
                    "ORGANIZATIONS",
                    "ORGANIZATIONS_SIL_SERVICE",
                    "DEBT_POSITIONS_TYPE",
                    "DEBT_POSITIONS_TYPE_ORG",
                    "DEBT_POSITIONS_TYPE_ORG_OPERATORS",
                    "ASSESSMENTS",
                    "ASSESSMENTS_REGISTRY",
                    "SEND_NOTIFICATION"
                ],
                "type": "string"
            },
            "UploadDetails": {
                "required": [
                    "fileName",
                    "filePathName",
                    "fileSize",
                    "ingestionFlowFileType",
                    "organizationId",
                    "status",
                    "uploadId"
                ],
                "type": "object",
                "properties": {
                    "creationDate": {
                        "type": "string",
                        "format": "date-time"
                    },
                    "updateDate": {
                        "type": "string",
                        "format": "date-time"
                    },
                    "updateOperatorExternalId": {
                        "type": "string"
                    },
                    "updateTraceId": {
                        "type": "string"
                    },
                    "uploadDetailId": {
                        "type": "integer",
                        "format": "int64"
                    },
                    "uploadId": {
                        "type": "integer",
                        "format": "int64"
                    },
                    "organizationId": {
                        "type": "integer",
                        "format": "int64"
                    },
                    "ingestionFlowFileId": {
                        "type": "integer",
                        "format": "int64"
                    },
                    "ingestionFlowFileType": {
                        "$ref": "#/components/schemas/IngestionFlowFileTypeEnum"
                    },
                    "filePathName": {
                        "type": "string"
                    },
                    "fileName": {
                        "type": "string"
                    },
                    "fileSize": {
                        "type": "integer",
                        "format": "int64"
                    },
                    "status": {
                        "$ref": "#/components/schemas/IngestionFlowFileStatus"
                    },
                    "errorDescription": {
                        "type": "string"
                    },
                    "discardFileName": {
                        "type": "string"
                    },
                    "numTotalRows": {
                        "type": "integer",
                        "format": "int64"
                    },
                    "numCorrectlyImportedRows": {
                        "type": "integer",
                        "format": "int64"
                    }
                }
            }
        }
    },
    "tags": [
        {
            "name": "migration-file",
            "description": "the migration-file API"
        }
    ]
}